version: "3.9"

services:
  rabbitmq:
    image: rabbitmq:3.13-management
    container_name: jobqueue-rabbitmq
    ports:
      - "5672:5672"     # AMQP (your Go apps use this)
      - "15672:15672"   # Web UI
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
